### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by GabrielOnDelphi** [djjd47130/JDLib#1]
JDLib-master\Test\JDCompsTest.dpr  cannot be compiled because DesignEditors, DesignIntf not found.
D10.4

**Comment by djjd47130** [comment]
While I see this is an old issue and has been closed, I can only suspect something being done wrong. The test application should not in any way be trying to compile anything design-time editor related. My best guess is that you added these files to the project manually. `DesignEditors` and `DesignIntf` are ONLY capable of compiling within a design-time package - nowhere else. This is due to an old copyright issue on Embarcadero's / Borland's end, if I recall.
